query facebookContentAll($id: String!, $token: String!) {
  getFacebookPageContent(id: $id, token: $token) {
    id
    description
    published_posts {
      data {
        story
        created_time
        id
      }
    }
    videos {
      data {
        id
        updated_time
        description
      }
    }
  }
}
